### ISSUE TITLE
Malicious user can cancel his `RetryableTicket` on L2 and loose depositors funds

### ISSUE THREAD

**Issue by NicolaMirchev** [TheSyntegrity/Juicebox_V4_Findings#30]
## Description 

Inside `JBArbitrumSucker` when we bridge from L1 -> L2, we call `_toL2`, which internally calls `ARBINBOX.createRetryableTicket`. The problem here is that we set `callValueRefundAddress : msg.sender` , which is a role with critical permission -> to cancel the ticket on L2, if the automatic redemption fails. The problem is that anyone can call `toRemote` with any `msg.value`. The function is responsible for bridging important information (merkle root), which is responsible for minting user project tokens on the destination. 
If there is a problem with the execution on the L2 (L2 gas price has increased unexpectedly, or something else), the untrusted user can cancel the ticket on L2, which will only refund the native funds, but will delete the message, undelivered, which will result in not updating the root on destination. Here is the page from arb doc [explaining different possible flows](https://docs.arbitrum.io/how-arbitrum-works/arbos/l1-l2-messaging). Note that if we bridge native funds, the impact will be larger, because they will be stolen with while being refunded to the beneficiary.
Here is the code of the [ArbRetryableTx](https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbRetryableTx.go) executable.

## Recommendation 
Set `callValueRefundAddress` to a project trusted owner address.

**Comment by mejango** [comment]
merged
